"""Audit report writer + questions/discrepancies append.

Outputs:
- `index/audits/lint_YYYYMMDD_HHMM.md` — immutable per-run report.
- Append to `wiki/questions.md` for findings requiring a researcher decision.
- Append to `wiki/discrepancies.md` for Check 7 (confidence conflicts) only.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from researchwiki.lint import Finding


def write_audit_report(
    *,
    report_path: Path,
    findings: list[Finding],
    pages_scanned: int,
    config_summary: dict,
    strict: bool,
    partial_run_note: str | None = None,
) -> None:
    """Write the immutable per-run audit report under `index/audits/`."""
    report_path.parent.mkdir(parents=True, exist_ok=True)
    now = datetime.now()

    counts = _severity_counts(findings)
    summary_table = (
        "| Severity | Count |\n"
        "|----------|-------|\n"
        f"| error    | {counts['error']:5d} |\n"
        f"| warn     | {counts['warn']:5d} |\n"
        f"| info     | {counts['info']:5d} |\n"
    )

    findings_text = "\n".join(_render_finding(f) for f in findings) if findings else "(none)\n"

    config_lines = "\n".join(f"- {k}: {v}" for k, v in config_summary.items())

    partial = f"\n⚠ {partial_run_note}\n" if partial_run_note else ""

    body = (
        f"# Lint audit — {now.strftime('%Y-%m-%d %H:%M')} ({_tz_label(now)})\n"
        f"_Generated by wiki-lint. Immutable once written._\n\n"
        f"## Repository\n"
        f"- Pages scanned: {pages_scanned}\n"
        f"- Strict mode: {str(strict).lower()}\n"
        f"{config_lines}\n"
        f"{partial}\n"
        f"## Summary\n"
        f"{summary_table}\n"
        f"## Findings\n\n"
        f"{findings_text}"
    )
    report_path.write_text(body, encoding="utf-8")


def append_questions(
    questions_md: Path,
    findings: list[Finding],
) -> int:
    """Append findings (excluding orphan info — those are not actionable
    questions per se — and excluding Check 7 contradictions which go to
    discrepancies.md instead) to `wiki/questions.md`. Returns the count
    of finding entries appended.
    """
    actionable = [
        f for f in findings
        if f.category != "contradictions" and not (f.category == "orphans" and f.severity == "info")
    ]
    if not actionable:
        return 0

    questions_md.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    block_lines = [f"\n## [{timestamp}] from wiki-lint\n"]
    for f in actionable:
        block_lines.append(_render_question_entry(f))

    existing = questions_md.read_text(encoding="utf-8") if questions_md.exists() else ""
    if existing and not existing.endswith("\n"):
        existing += "\n"
    questions_md.write_text(existing + "\n".join(block_lines), encoding="utf-8")
    return len(actionable)


def append_discrepancies(
    discrepancies_md: Path,
    findings: list[Finding],
) -> int:
    """Append Check 7 findings (confidence conflicts) to
    `wiki/discrepancies.md`. Returns the count appended."""
    contradictions = [f for f in findings if f.category == "contradictions"]
    if not contradictions:
        return 0

    discrepancies_md.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    block_lines = [f"\n## [{timestamp}] from wiki-lint\n"]
    for f in contradictions:
        block_lines.append(
            f"**Confidence conflict on `{f.page}`:**\n"
            f"  {f.message}\n\n"
            f"Reconcile per P7 — confidence is a property of the binding evidence, "
            f"not the page that records it.\n"
        )

    existing = discrepancies_md.read_text(encoding="utf-8") if discrepancies_md.exists() else ""
    if existing and not existing.endswith("\n"):
        existing += "\n"
    discrepancies_md.write_text(existing + "\n".join(block_lines), encoding="utf-8")
    return len(contradictions)


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------


def _severity_counts(findings: list[Finding]) -> dict[str, int]:
    counts = {"error": 0, "warn": 0, "info": 0}
    for f in findings:
        counts[f.severity] = counts.get(f.severity, 0) + 1
    return counts


def _render_finding(f: Finding) -> str:
    head = f"### {f.severity} · {f.category} · {f.page}"
    line_part = f" (line {f.line})" if f.line else ""
    return (
        f"{head}{line_part}\n"
        f"{f.message}\n"
        f"Source rule: {f.source_rule}\n"
    )


def _render_question_entry(f: Finding) -> str:
    head = f"**{_human_category(f.category)} · {f.severity}** — `{f.page}`"
    return (
        f"{head}\n"
        f"{f.message}\n"
        f"Source: {f.source_rule}\n"
    )


def _human_category(category: str) -> str:
    return {
        "frontmatter": "Frontmatter violation",
        "links": "Link issue",
        "speculation": "Speculation density",
        "stale": "Persistent stale ref",
        "orphans": "Orphan page",
    }.get(category, category)


def _tz_label(dt: datetime) -> str:
    tz = dt.astimezone().tzname()
    return tz or "local"
